name: Replace Text and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if you deploy from a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace text in index.html
        run: |
          sed -i "s/MY_NAME/${{ secrets.NAME }}/g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build and Deploy
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./  # Adjust the path if necessary

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
