name: Replace Text and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if you deploy from a different branch

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace text in index.html
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
        run: |
          sed -i "s/MY_NAME/${MY_NAME}/g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build and Deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
